apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
spec:
  # Usamos la clase de almacenamiento por defecto que viene con Docker Desktop(Puede averiguarse con el comando
  # "kubectl get (sc|storageclass|storageclasses)".
  storageClassName: hostpath
  capacity:
    # Para indicar gigas sería Gi. Por ejemplo, 2Gi.
    storage: 500Mi
  # Opcional porque es el valor por defecto.
  volumeMode: Filesystem
  # En nuestro caso, usamos la palabra "Once" para indicar que sólo vamos a leer y a escribir desde un sólo nodo
  # porque estamos usando Docker Desktop y sólo hay un "worker node". Por lo tanto, todos los Pods se ejecutarán
  # desde ese "worker node".
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data