apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
spec:
  # Reclamamos el PersistentVolume "pv-postgres".
  volumeName: pv-postgres
  # Indicamos la misma clase de almacenamiento que se usa en el PersistentVolume.
  storageClassName: hostpath
  # Indicamos los mismos accesos que en el PersistentVolume.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Tiene que ser un tamaño igual o menor a la capacidad del PersistentVolume solicitado.
      storage: 500Mi