apiVersion: v1
kind: Secret
metadata:
  name: mysql8
type: Opaque
data:
  db_root_password: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres14
type: Opaque
data:
  db_password: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  spring.datasource.username: cm9vdA==
  spring.datasource.password: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  spring.datasource.username: cG9zdGdyZXM=
  spring.datasource.password: cm9vdA==
